alias vpn-start="sudo systemctl start wg-quick@wg1.service"
alias vpn-stop="sudo systemctl stop wg-quick@wg1.service"
alias vpn-status="sudo systemctl status wg-quick@wg1.service"
alias vpn-enable="sudo systemctl enable wg-quick@wg1.service"
alias vpn-disable="sudo systemctl disable wg-quick@wg1.service"